let arr = [
  { name: `Aci Bonaccorsi`, value: `aci+bonaccorsi` },
  { name: `Aci Castello`, value: `aci+castello` },
  { name: `Aci Catena`, value: `aci+catena` },
  { name: `Aci S.Antonio`, value: `aci+sant'antonio` },
  { name: `Acireale`, value: `acireale` },
  { name: `Adrano`, value: `adrano` },
  { name: `Belpasso`, value: `belpasso` },
  { name: `Biancavilla`, value: `biancavilla` },
  { name: `Bronte`, value: `bronte` },
  { name: `Calatabiano`, value: `calatabiano` },
  { name: `Caltagirone`, value: `caltagirone` },
  { name: `Camporotondo Etneo`, value: `camporotondo+etneo` },
  { name: `Castel di Judica`, value: `castel+di+judica` },
  { name: `Castiglione di Sicilia`, value: `castiglione+di+sicilia` },
  { name: `Catania`, value: `catania` },
  { name: `Fiumefreddo`, value: `fiumefreddo+di+sicilia` },
  { name: `Giarre`, value: `giarre` },
  { name: `Grammichele`, value: `grammichele` },
  { name: `Gravina di Catania`, value: `gravina+di+Catania` },
  { name: `Licodia Eubea`, value: `licodia+eubea` },
  { name: `Linguaglossa`, value: `linguaglossa` },
  { name: `Maletto`, value: `maletto` },
  { name: `Maniace`, value: `maniace` },
  { name: `Mascali`, value: `mascali` },
  { name: `Mascalucia`, value: `mascalucia` },
  { name: `Mazzarrone`, value: `mazzarrone` },
  { name: `Militello in val di Catania`, value: `militello+in+val+di+catania` },
  { name: `Milo`, value: `milo` },
  { name: `Mineo`, value: `Mineo` },
  { name: `Mirabella Imbaccari`, value: `mirabella+imbaccari` },
  { name: `Misterbianco`, value: `misterbianco` },
  { name: `Motta Santa'Anastasia`, value: `motta+sant'anastasia` },
  { name: `Nicolosi`, value: `nicolosi` },
  { name: `Palagonia`, value: `palagonia` },
  { name: `Paterno'`, value: `paterno` },
  { name: `Pedara`, value: `pedara` },
  { name: `Piedimonte Etneo`, value: `piedimonte+etneo` },
  { name: `Raddusa`, value: `raddusa` },
  { name: `Ragalna`, value: `ragalna` },
  { name: `Ramacca`, value: `ramacca` },
  { name: `Randazzo`, value: `randazzo` },
  { name: `Riposto`, value: `riposto` },
  { name: `San Cono`, value: `san+cono` },
  { name: `San Giovanni La Punta`, value: `san+giovanni+la+punta` },
  { name: `San Gregorio`, value: `san+gregorio+di+catania` },
  { name: `San Michele di Ganzaria`, value: `san+michele+di+ganzaria` },
  { name: `San Pietro Clarenza`, value: `san+pietro+clarenza` },
  { name: `Santa Maria di Licodia`, value: `santa+maria+di+licodia` },
  { name: `Santa Venerina`, value: `santa+venerina` },
  { name: `Sant'Agata Li Battiati`, value: `sant'agata+li+battiati` },
  { name: `Sant'Alfio`, value: `sant'alfio` },
  { name: `Scordia`, value: `scordia` },
  { name: `Trecastagni`, value: `trecastagni` },
  { name: `Tremestieri Etneo`, value: `tremestieri+etneo` },
  { name: `Valverde`, value: `valverde` },
  { name: `Viagrande`, value: `viagrande` },
  { name: `Vizzini`, value: `vizzini` },
  { name: `Zafferana Etnea`, value: `zafferana+etnea` },
];

export default arr;
